//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blueprint.UAS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UASEntityContainer : DbContext
    {
        public UASEntityContainer()
            : base("name=UASEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Org> OrgSet { get; set; }
        public virtual DbSet<Dept> DeptSet { get; set; }
        public virtual DbSet<Empl> EmplSet { get; set; }
        public virtual DbSet<Rule> RuleSet { get; set; }
        public virtual DbSet<Auth> AuthSet { get; set; }
    }
}
